from django.contrib import admin

# Register the models inside polls/admin.py, so
# that the "polls" app and its models appear on
# the admin page.
from .models import Question, Choice


"""Upon creating a new Question object, three
   empty fields will be provided for the sake
   of instantiating three Choice objects that
   will belong to the newly generated Question."""
# class ChoiceInline(admin.StackedInline):
class ChoiceInline(admin.TabularInline):
  model = Choice
  extra = 3


class QuestionAdmin(admin.ModelAdmin):
  # fields = ["pub_date", "question_text"]
  fieldsets = [
    # Dictates the order in which the data fields
    # are displayed on the admin page.

    # Use the same names for the attributes as the
    # ones declared inside the models.py file.
    (None, {"fields": ["question_text"]}),
    # ("Date information", {"fields": ["pub_date"]}),
    ("Date information",
     {"fields": ["pub_date"], "classes": ["collapse"]}
    ),
  ]

  inlines = [ChoiceInline]

# The outcome of registering the "Question" model, is that
# a default form representation is generated by Django for it.
admin.site.register(Question, QuestionAdmin)

# admin.site.register(Choice)